import bcrypt from 'bcryptjs';

export const defaultQuestions = [
    { id: 1, text: "Which environment do you prefer working in?", type: "personality", category: "Work Environment", options: [{ text: "Fast-paced and dynamic", value: "dynamic", category: "Software Engineer", weight: 3 }, { text: "Quiet and focused", value: "focused", category: "Data Scientist", weight: 3 }, { text: "Collaborative and social", value: "social", category: "Project Manager", weight: 3 }, { text: "Structured and orderly", value: "structured", category: "Systems Analyst", weight: 3 }] },
    { id: 2, text: "What kind of problems do you enjoy solving most?", type: "skill", category: "Problem Solving", options: [{ text: "Technical or logical puzzles", value: "logic", category: "Software Engineer", weight: 3 }, { text: "Analyzing patterns and data", value: "data", category: "Data Scientist", weight: 3 }, { text: "Organizing people and schedules", value: "people", category: "Project Manager", weight: 3 }, { text: "Designing user experiences", value: "design", category: "UX Designer", weight: 3 }] },
    { id: 3, text: "How do you feel about learning new technologies?", type: "personality", category: "Adaptability", options: [{ text: "I love it and do it constantly", value: "high", category: "Software Engineer", weight: 3 }, { text: "I like it when it's necessary", value: "medium", category: "IT Consultant", weight: 2 }, { text: "I prefer sticking to what I know", value: "low", category: "Quality Assurance", weight: 1 }] },
    { id: 4, text: "How do you prefer to communicate at work?", type: "personality", category: "Communication", options: [{ text: "Written documentation and emails", value: "written", category: "Technical Writer", weight: 3 }, { text: "Face-to-face meetings", value: "verbal", category: "Project Manager", weight: 3 }, { text: "Code and technical specs", value: "code", category: "Software Engineer", weight: 3 }, { text: "Visual diagrams and prototypes", value: "visual", category: "UX Designer", weight: 3 }] },
    { id: 5, text: "What motivates you most in your work?", type: "personality", category: "Motivation", options: [{ text: "Building innovative products", value: "innovation", category: "Software Engineer", weight: 3 }, { text: "Finding insights from data", value: "insights", category: "Data Scientist", weight: 3 }, { text: "Leading and mentoring teams", value: "leadership", category: "Project Manager", weight: 3 }, { text: "Creating beautiful interfaces", value: "aesthetics", category: "UX Designer", weight: 3 }] },
    { id: 6, text: "Which subject did you enjoy most in school?", type: "skill", category: "Academic Interest", options: [{ text: "Mathematics and Logic", value: "math", category: "Data Scientist", weight: 3 }, { text: "Computer Science", value: "cs", category: "Software Engineer", weight: 3 }, { text: "Arts and Design", value: "art", category: "UX Designer", weight: 3 }, { text: "Business and Management", value: "business", category: "Project Manager", weight: 3 }] },
    { id: 7, text: "How do you handle deadlines and pressure?", type: "personality", category: "Stress Management", options: [{ text: "I thrive under pressure", value: "thrive", category: "Software Engineer", weight: 2 }, { text: "I plan ahead to avoid stress", value: "plan", category: "Project Manager", weight: 3 }, { text: "I focus on quality over speed", value: "quality", category: "Quality Assurance", weight: 3 }, { text: "I break tasks into pieces", value: "breakdown", category: "Systems Analyst", weight: 2 }] },
    { id: 8, text: "Which skill would you most like to develop?", type: "skill", category: "Growth Areas", options: [{ text: "Machine learning & AI", value: "ml", category: "Data Scientist", weight: 3 }, { text: "Full-stack web development", value: "fullstack", category: "Software Engineer", weight: 3 }, { text: "Leadership & communication", value: "leadership", category: "Project Manager", weight: 3 }, { text: "UI/UX research & design", value: "ux", category: "UX Designer", weight: 3 }] },
    { id: 9, text: "How do you approach decision making?", type: "personality", category: "Decision Making", options: [{ text: "Data-driven with analysis", value: "analytical", category: "Data Scientist", weight: 3 }, { text: "Intuition with experience", value: "intuitive", category: "UX Designer", weight: 2 }, { text: "Consensus through discussion", value: "consensus", category: "Project Manager", weight: 3 }, { text: "Quick experimentation", value: "experimental", category: "Software Engineer", weight: 2 }] },
    { id: 10, text: "What type of projects excite you the most?", type: "skill", category: "Project Preference", options: [{ text: "Building apps and software", value: "apps", category: "Software Engineer", weight: 3 }, { text: "Analyzing trends & predictions", value: "analysis", category: "Data Scientist", weight: 3 }, { text: "Managing cross-functional teams", value: "management", category: "Project Manager", weight: 3 }, { text: "Redesigning digital experiences", value: "redesign", category: "UX Designer", weight: 3 }] },
    { id: 11, text: "How do you feel about working with hardware and infrastructure?", type: "skill", category: "Technical Focus", options: [{ text: "I love configuring servers and networks", value: "infra", category: "DevOps Engineer", weight: 4 }, { text: "I prefer working on the application layer", value: "app", category: "Software Engineer", weight: 2 }, { text: "I enjoy high-level system architecture", value: "arch", category: "Systems Analyst", weight: 3 }] },
    { id: 12, text: "Which of these interests you most in a digital product?", type: "personality", category: "Product Perspective", options: [{ text: "How it's secured from hackers", value: "security", category: "Cyber Security", weight: 4 }, { text: "How the data is processed", value: "data", category: "Data Scientist", weight: 3 }, { text: "How it meets user needs", value: "user", category: "UX Designer", weight: 3 }] },
    { id: 13, text: "How do you like to spend your free time?", type: "personality", category: "Interests", options: [{ text: "Solving puzzles or coding projects", value: "puzzles", category: "Software Engineer", weight: 3 }, { text: "Reading about business and trends", value: "business", category: "Project Manager", weight: 3 }, { text: "Experimenting with creative arts", value: "creative", category: "UX Designer", weight: 3 }, { text: "Building or fixing gadgets", value: "gadgets", category: "IT Consultant", weight: 3 }] },
    { id: 14, text: "How comfortable are you with public speaking?", type: "skill", category: "Social", options: [{ text: "Very comfortable, I enjoy leading", value: "high", category: "Project Manager", weight: 4 }, { text: "I prefer small team discussions", value: "medium", category: "Software Engineer", weight: 2 }, { text: "I'd rather let my work speak for itself", value: "low", category: "Data Scientist", weight: 2 }] },
    { id: 15, text: "What is your stance on artificial intelligence?", type: "personality", category: "Technology", options: [{ text: "It's the future and I want to build it", value: "ai", category: "AI Engineer", weight: 5 }, { text: "It's a powerful tool for productivity", value: "tool", category: "Software Engineer", weight: 2 }, { text: "I'm concerned about the ethics and data", value: "ethics", category: "Data Scientist", weight: 2 }] },
    { id: 16, text: "Where do you prefer to run your code or store data?", type: "skill", category: "Architecture", options: [{ text: "On the Cloud (AWS, Azure, GCP)", value: "cloud", category: "DevOps Engineer", weight: 4 }, { text: "On local high-performance servers", value: "local", category: "Systems Analyst", weight: 3 }, { text: "On edge devices or IoT", value: "edge", category: "Software Engineer", weight: 2 }] },
    { id: 17, text: "What type of devices do you use most?", type: "personality", category: "Usage", options: [{ text: "Mobile phones and tablets", value: "mobile", category: "Software Engineer", weight: 3 }, { text: "Laptops and Desktops", value: "web", category: "Full Stack Developer", weight: 3 }, { text: "Game consoles or VR", value: "gaming", category: "Game Developer", weight: 4 }] },
    { id: 18, text: "How do you feel about working with visual aesthetics?", type: "personality", category: "Creative", options: [{ text: "I care about every pixel", value: "high", category: "UX Designer", weight: 4 }, { text: "I care about functionality first", value: "medium", category: "Software Engineer", weight: 2 }, { text: "I'd rather work on logic and data", value: "low", category: "Data Scientist", weight: 3 }] },
    { id: 19, text: "What's your ideal work-life setup?", type: "personality", category: "Lifestyle", options: [{ text: "Fully Remote", value: "remote", category: "Software Engineer", weight: 3 }, { text: "Hybrid / Flexible", value: "hybrid", category: "Project Manager", weight: 3 }, { text: "In-office with a team", value: "office", category: "IT Consultant", weight: 3 }] },
    { id: 20, text: "How do you approach large datasets?", type: "skill", category: "Data", options: [{ text: "Applying complex algorithms", value: "algo", category: "Data Scientist", weight: 4 }, { text: "Ensuring data integrity and security", value: "security", category: "Cyber Security", weight: 4 }, { text: "Optimizing database queries", value: "db", category: "Software Engineer", weight: 3 }] },
    { id: 21, text: "Which programming philosophy do you support?", type: "personality", category: "Philosophy", options: [{ text: "Open Source and Community driven", value: "open", category: "Software Engineer", weight: 3 }, { text: "Enterprise and Secure solutions", value: "enterprise", category: "Cyber Security", weight: 3 }, { text: "Fast-to-market and lean startups", value: "lean", category: "AI Engineer", weight: 3 }] },
    { id: 22, text: "Would you rather lead a team or build independently?", type: "personality", category: "Leadership", options: [{ text: "Lead and coordinate others", value: "lead", category: "Project Manager", weight: 5 }, { text: "Build deep technical features alone", value: "build", category: "Software Engineer", weight: 3 }, { text: "Act as a technical bridge (Hybrid)", value: "bridge", category: "Systems Analyst", weight: 3 }] }
];

export const careerDetails = {
    "Software Engineer": { title: "Software Engineer", description: "Build robust, scalable software applications and systems.", skills: ["JavaScript/TypeScript", "React", "Node.js", "System Design", "Algorithms"], avgSalary: "$110k - $160k", growth: "High (22% projection)", difficulty: "Challenging", learningPath: ["Learn Core Programming", "Master a Framework", "Build Portfolios", "Learn Cloud Computing"] },
    "Data Scientist": { title: "Data Scientist", description: "Extract insights from complex data to drive business decisions.", skills: ["Python", "Machine Learning", "Statistics", "SQL", "Data Visualization"], avgSalary: "$105k - $155k", growth: "Very High (36% projection)", difficulty: "High", learningPath: ["Learn Data Analysis", "Master Python/R", "Learn ML Models", "Understand Business Context"] },
    "Project Manager": { title: "IT Project Manager", description: "Lead teams to deliver technology projects on time and within budget.", skills: ["Agile/Scrum", "Risk Management", "Leadership", "Budgeting", "Communication"], avgSalary: "$95k - $145k", growth: "Stable", difficulty: "Moderate", learningPath: ["Project Management Basics", "Get Certified (PMP/CSM)", "Learn Tools like Jira", "Soft Skills Mastery"] },
    "UX Designer": { title: "UX/UI Designer", description: "Create beautiful, user-centered digital experiences.", skills: ["Figma", "User Research", "Wireframing", "Prototyping", "Visual Design"], avgSalary: "$85k - $130k", growth: "High", difficulty: "Creative", learningPath: ["Design Fundamentals", "Master Figma/Adobe XD", "Build Case Studies", "Learn Basic Accessibility"] },
    "Cyber Security": { title: "Cyber Security Analyst", description: "Protect organization networks and data from cyber threats.", skills: ["Network Security", "Ethical Hacking", "Cryptography", "Incident Response"], avgSalary: "$100k - $150k", growth: "Explosive (33% projection)", difficulty: "Critical", learningPath: ["CompTIA Security+", "Ethical Hacking Course", "Network Fundamentals", "Cloud Security"] },
    "DevOps Engineer": { title: "DevOps Engineer", description: "Automate and optimize the software development lifecycle.", skills: ["Docker/Kubernetes", "AWS/GCP", "CI/CD Pipelines", "Linux", "Terraform"], avgSalary: "$120k - $170k", growth: "Very High", difficulty: "Technical", learningPath: ["Learn Linux", "Master Containerization", "CI/CD Certification", "Cloud Infrastructure"] },
    "AI Engineer": { title: "AI Engineer", description: "Develop and implement advanced AI models and neural networks.", skills: ["PyTorch/TensorFlow", "Deep Learning", "LLMs", "Mathematics", "NLP"], avgSalary: "$130k - $200k", growth: "Skyrocketing", difficulty: "Expert", learningPath: ["Python Mastery", "Advanced Math & Stats", "Core ML Algorithms", "Deep Learning Architectures"] },
    "Game Developer": { title: "Game Developer", description: "Design and build immersive digital games and interactive experiences.", skills: ["C# / C++", "Unity / Unreal Engine", "3D Modeling", "Physics", "VFX"], avgSalary: "$80k - $140k", growth: "Steady", difficulty: "High (Artistic + Technical)", learningPath: ["Learn C#/C++", "Master Unity/Unreal", "Math for Games", "Create a Game Demo"] },
    "Full Stack Developer": { title: "Full Stack Developer", description: "Develop both client-side and server-side components of web applications.", skills: ["React/Next.js", "Node.js", "SQL/NoSQL Databases", "Cloud APIs", "DevOps Basics"], avgSalary: "$100k - $150k", growth: "High (Universal Demand)", difficulty: "Moderate-High", learningPath: ["Frontend Mastery", "Backend/API Design", "Database Management", "Deploy Full Projects"] }
};

export async function seedDatabase(db) {
    const usersCount = await db.collection('users').countDocuments();
    if (usersCount === 0) {
        const hashedPassword = await bcrypt.hash('admin123', 10);
        await db.collection('users').insertOne({ name: 'Admin', email: 'admin@careerwise.com', password: hashedPassword, role: 'admin', createdAt: new Date() });
        await db.collection('users').insertOne({ name: 'Sravani', email: 'sravanigorentla205@careerwise.com', password: hashedPassword, role: 'admin', createdAt: new Date() });
    }
    await db.collection('questions').deleteMany({});
    await db.collection('questions').insertMany(defaultQuestions);
}
